mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.virtualspider.blog
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog1
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  port: 80