#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: cn.virtualspider.blog
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog1?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
#  http:
#    multipart:
#      location: d:/tmp
server:
  port: 80
custom:
  tmpLocation: d:/tmp
  resourceLocation: /upload/